/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OsRouteImport } from './routes/_os'
import { Route as OsIndexRouteImport } from './routes/_os/index'
import { Route as OsContactRouteImport } from './routes/_os/contact'
import { Route as OsExperienceRouteImport } from './routes/_os/experience'
import { Route as OsInfrastructureRouteImport } from './routes/_os/infrastructure'
import { Route as OsProjectsRouteImport } from './routes/_os/projects'
import { Route as OsStackRouteImport } from './routes/_os/stack'

const OsRoute = OsRouteImport.update({
  id: '/_os',
  getParentRoute: () => rootRouteImport,
} as any)
const OsIndexRoute = OsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OsRoute,
} as any)
const OsContactRoute = OsContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => OsRoute,
} as any)
const OsExperienceRoute = OsExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => OsRoute,
} as any)
const OsInfrastructureRoute = OsInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => OsRoute,
} as any)
const OsProjectsRoute = OsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => OsRoute,
} as any)
const OsStackRoute = OsStackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => OsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof OsIndexRoute
  '/contact': typeof OsContactRoute
  '/experience': typeof OsExperienceRoute
  '/infrastructure': typeof OsInfrastructureRoute
  '/projects': typeof OsProjectsRoute
  '/stack': typeof OsStackRoute
}
export interface FileRoutesByTo {
  '/contact': typeof OsContactRoute
  '/experience': typeof OsExperienceRoute
  '/infrastructure': typeof OsInfrastructureRoute
  '/projects': typeof OsProjectsRoute
  '/stack': typeof OsStackRoute
  '/': typeof OsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_os': typeof OsRouteWithChildren
  '/_os/contact': typeof OsContactRoute
  '/_os/experience': typeof OsExperienceRoute
  '/_os/infrastructure': typeof OsInfrastructureRoute
  '/_os/projects': typeof OsProjectsRoute
  '/_os/stack': typeof OsStackRoute
  '/_os/': typeof OsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/experience'
    | '/infrastructure'
    | '/projects'
    | '/stack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contact'
    | '/experience'
    | '/infrastructure'
    | '/projects'
    | '/stack'
    | '/'
  id:
    | '__root__'
    | '/_os'
    | '/_os/contact'
    | '/_os/experience'
    | '/_os/infrastructure'
    | '/_os/projects'
    | '/_os/stack'
    | '/_os/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OsRoute: typeof OsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_os': {
      id: '/_os'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_os/': {
      id: '/_os/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof OsIndexRouteImport
      parentRoute: typeof OsRoute
    }
    '/_os/contact': {
      id: '/_os/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof OsContactRouteImport
      parentRoute: typeof OsRoute
    }
    '/_os/experience': {
      id: '/_os/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof OsExperienceRouteImport
      parentRoute: typeof OsRoute
    }
    '/_os/infrastructure': {
      id: '/_os/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof OsInfrastructureRouteImport
      parentRoute: typeof OsRoute
    }
    '/_os/projects': {
      id: '/_os/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof OsProjectsRouteImport
      parentRoute: typeof OsRoute
    }
    '/_os/stack': {
      id: '/_os/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof OsStackRouteImport
      parentRoute: typeof OsRoute
    }
  }
}

interface OsRouteChildren {
  OsContactRoute: typeof OsContactRoute
  OsExperienceRoute: typeof OsExperienceRoute
  OsInfrastructureRoute: typeof OsInfrastructureRoute
  OsProjectsRoute: typeof OsProjectsRoute
  OsStackRoute: typeof OsStackRoute
  OsIndexRoute: typeof OsIndexRoute
}

const OsRouteChildren: OsRouteChildren = {
  OsContactRoute: OsContactRoute,
  OsExperienceRoute: OsExperienceRoute,
  OsInfrastructureRoute: OsInfrastructureRoute,
  OsProjectsRoute: OsProjectsRoute,
  OsStackRoute: OsStackRoute,
  OsIndexRoute: OsIndexRoute,
}

const OsRouteWithChildren = OsRoute._addFileChildren(OsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  OsRoute: OsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
